#!/bin/bash
backup_dir={{ app.home_dir }}/backups/
mkdir -p $backup_dir
cd $backup_dir
name=$(date -I)
echo "Creating backup $name"
pg_dump --no-owner --no-acl cobl > $name.sql
echo "Compressing backup $name"
gzip -f $name.sql
curl -u"{{ osenv['CDSTAR_USER_BACKUP'] }}:{{ osenv['CDSTAR_PWD_BACKUP'] }}" -X POST -H "content-type: application/x-sql" --data-binary @"$name.sql.gz" https://cdstar.shh.mpg.de/bitstreams/{{ app.dbdump }}/$name
ls -tr *sql.gz | grep -v 'create\|dump.sql' | head -n -10 | xargs --no-run-if-empty rm
