#!/bin/bash
backup_dir={{ app.home_dir }}/backups/
mkdir -p $backup_dir
cd $backup_dir
name=$(date -I)
echo "Creating backup $name"
pg_dump --no-owner --no-acl cobl > $name.sql
echo "Compressing backup $name"
gzip -f $name.sql
ls -tr *sql.gz | grep -v 'create\|dump.sql' | head -n -10 | xargs --no-run-if-empty rm
