#!/bin/bash
# Name to use for the new database dump:
cd {{ app.home_dir }}/backups/
name=$(date -I)
echo "Creating database dump: $name.sql"
# Creating the dump:
mysqldump -hlocalhost -u{{ app.name }} -p{{ app.name }} --routines --single-transaction {{ app.name }} >> $name.sql
gzip -f $name.sql
# Keeping only 10 latest dumps:
# Compare https://stackoverflow.com/a/10119963/448591
ls -tr *sql.gz | grep -v 'create\|dump.sql' | head -n -10 | xargs --no-run-if-empty rm
